### ISSUE TITLE
Interested in using additonnal dataplane ?

### ISSUE THREAD

**Issue by frederic-loui** [rwestphal/holo#1]
Hi ! Love your project. We are from the [RARE](https://wiki.geant.org/display/RARE/Home) project and I was wondering if you'd be down to hook holo to different dataplane. We are using [freeRtr](http://www.freertr.org) which is a control plane from our community and it works great with different dataplane such as DPDK and INTEL P4 TOFINO. I'd would be curious, to conduct an experiment and "hook" holo to an additional control-plane. Please let me know your thoughts. Other than that kudos for your work. You raised very good idea ! And in rust-lang !

**Comment by rwestphal** [comment]
Hi Frederic,

Thanks for your kind words and interest in Holo!

I'd certainly appreciate contributions on that front. Currently Holo doesn't have the necessary abstractions to plug in different dataplanes, but we can definitely solve that with some refactoring. If you want to discuss this further, feel free to reach out to me on the project's Discord channel.

**Comment by frederic-loui** [comment]
Thanks ! Let's close this issue and pursue on Discord :-)
